# Generated by Django 4.1.1 on 2022-09-28 12:19

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Your Phone Number', max_length=31, null=True),
        ),
    ]
