# Generated by Django 4.1.1 on 2022-09-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='initial',
            field=models.CharField(default='mj', max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
