# Generated by Django 4.1.1 on 2022-09-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
