# Generated by Django 4.1.1 on 2022-09-29 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employee_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(max_length=5, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.AlterField(
            model_name='employee',
            name='initial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.initial'),
        ),
    ]
