# Generated by Django 4.1.1 on 2022-09-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_initial_remove_employee_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='doj',
            new_name='dateoj',
        ),
    ]
