# Generated by Django 4.1.1 on 2022-09-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_rename_doj_employee_dateoj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initial',
            old_name='initial',
            new_name='name',
        ),
    ]
