# Generated by Django 4.1.1 on 2022-09-29 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_alter_employee_doj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-doj']},
        ),
        migrations.AlterModelOptions(
            name='initial',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
